export const siteConfig = {
  name: "Jay Kamble | Full Stack Developer | Next.js & React Developer Portfolio",
  description: "Jay Kamble is a Full Stack Developer from Chhatrapati Sambhajinagar (Aurangabad), Maharashtra. A B.Sc. Information Technology Graduate specializing as a Next.js Developer and React Developer. Explore the portfolio of Jay Kamble (JayKamble009).",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://jaykamble009.in",
  ogImage: "/og/portfolio-banner.png",
  featuredRepos: ["pdfino", "classquiz", "event-management"],
  links: {
    twitter: "https://twitter.com/jaykamble",
    github: "https://github.com/jaykamble009",
    linkedin: "https://www.linkedin.com/in/jay-kamble-425892366"
  },
  creator: "Jay Kamble",
  author: "Jay Kamble",
  location: "Chhatrapati Sambhajinagar, Maharashtra, India",
  keywords: [
    "Jay Kamble",
    "JayKamble",
    "Jay Kamble Portfolio",
    "Jay Kamble Developer",
    "Jay Kamble Full Stack Developer",
    "Jay Kamble Software Engineer",
    "Jay Kamble Software Developer",
    "Jay Kamble Web Developer",
    "Jay Kamble React Developer",
    "Jay Kamble Next.js Developer",
    "Jay Kamble TypeScript Developer",
    "JayKamble009",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Node.js Developer",
    "Express.js Developer",
    "Web Application Developer",
    "Modern Web Developer",
    "Software Engineer",
    "Software Developer",
    "Open Source Developer",
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express.js",
    "Tailwind CSS",
    "PostgreSQL",
    "Firebase",
    "Supabase",
    "Git",
    "GitHub",
    "REST API",
    "Responsive Web Design",
    "SEO Optimization",
    "Performance Optimization",
    "Jay Kamble Chhatrapati Sambhajinagar",
    "Jay Kamble Aurangabad",
    "Aurangabad Full Stack Developer",
    "Chhatrapati Sambhajinagar Developer",
    "Maharashtra Software Developer",
    "India Full Stack Developer",
    "Jay Kamble Maharashtra",
    "Jay Kamble India",
    "B.Sc Information Technology",
    "B.Sc IT Graduate",
    "Information Technology Graduate",
    "Deogiri College",
    "Dr. Babasaheb Ambedkar Marathwada University",
    "Hire React Developer",
    "Hire Full Stack Developer",
    "Portfolio of Full Stack Developer",
    "Developer Portfolio",
    "Software Engineer Portfolio",
    "React Portfolio",
    "Next.js Portfolio",
    "JavaScript Portfolio",
    "Frontend Portfolio",
    "Web Developer Portfolio",
    "AI Developer",
    "AI Engineer",
    "AI SaaS Developer",
    "SaaS Developer",
    "PDF Editor Developer",
    "Restaurant Management Software",
    "QR Ordering System",
    "Next.js SaaS",
    "React SaaS",
    "AI Web Applications"
  ]
}
